name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest
        go mod tidy

    - name: Test
      run: |
        export CGO_ENABLED=0
        export PATH=$PATH:$(go env GOPATH)/bin
        go vet ./...
        go test ./...
        staticcheck ./...
        govulncheck ./...

    - name: Build
      run: go build -v .
